services:
    console:
        image: khulnasoft/getapp-console:dev
        build:
            context: .
            args:
                PUBLIC_CONSOLE_MODE: ${PUBLIC_CONSOLE_MODE}
                PUBLIC_GETAPP_ENDPOINT: ${PUBLIC_GETAPP_ENDPOINT}
                PUBLIC_GROWTH_ENDPOINT: ${PUBLIC_GROWTH_ENDPOINT}
                PUBLIC_STRIPE_KEY: ${PUBLIC_STRIPE_KEY}
                SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
        develop:
            watch:
                - action: rebuild
                  path: ./
                  ignore:
                      - .github
                      - tests/
                      - node_modules/
                      - build/
        environment:
            - PUBLIC_CONSOLE_MODE
            - PUBLIC_GETAPP_ENDPOINT
            - PUBLIC_GROWTH_ENDPOINT
            - PUBLIC_STRIPE_KEY
        ports:
            - '3000:80'
